build:
    environment:
        php:
            version: 5.5.12
    dependencies:
        before:
            - sudo composer self-update && composer --version
            - composer global require "fxp/composer-asset-plugin:1.0.0"
    tests:
        override:
            - phpunit
imports:
    - php
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_sim: false
    php_cpd: false
    php_pdepend: true
    php_analyzer: true
    php_changetracking: true
    external_code_coverage: true
filter:
    excluded_paths:
        - tests/*
        - vendor/*
